# Generated by Django 4.0.2 on 2022-02-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_geeksmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='geeks', through='api.Cart', to='api.ProductsModel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='geek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geeksmodel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productsmodel'),
        ),
    ]
